name: Deploy FoodBot

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: discord-bot

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update yaml files
        run: |
          sed -i "s/dummy_CLIENTID/${{ secrets.DISCORD_CLIENTID }}/g" values.yaml
          sed -i "s/dummy_GUILDID/${{ secrets.DISCORD_GUILDID }}/g" values.yaml
          sed -i "s/dummy_TOKEN/${{ secrets.DISCORD_TOKEN }}/g" values.yaml
          sed -i "s/dummy_DOCKERCONFIG/${{ secrets.GHCR_DOCKERCONFIG }}/g" values.yaml

      - name: Helm Deploy
        run: helm upgrade --install foodbot ./helm-chart
