name: Deploy FoodBot

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update yaml files
        run: |
          sed -i "s/dummy_CLIENTID/${{ secrets.DISCORD_CLIENTID }}/g" helm-chart/values.yaml
          sed -i "s/dummy_GUILDID/${{ secrets.DISCORD_GUILDID }}/g" helm-chart/values.yaml
          sed -i "s/dummy_TOKEN/${{ secrets.DISCORD_TOKEN }}/g" helm-chart/values.yaml
          sed -i "s/dummy_DOCKERCONFIGJSON/${{ secrets.DOCKERCONFIGJSON }}/g" helm-chart/values.yaml

      - name: Helm Deploy
        run: helm upgrade --install foodbot ./helm-chart
