name: Deploy FoodBot

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update yaml files
        run: |
          sed -i "s/dummy_CLIENTID/${{ secrets.DISCORD_CLIENTID }}/g" helm-chart/values.yaml
          sed -i "s/dummy_GUILDID/${{ secrets.DISCORD_GUILDID }}/g" helm-chart/values.yaml
          sed -i "s/dummy_TOKEN/${{ secrets.DISCORD_TOKEN }}/g" helm-chart/values.yaml

      - name: Create GHCR Secret
        run: kubectl create secret docker-registry ghc-secret --docker-server=ghcr.io --docker-username=${{ github.actor }} --docker-password=${{ secrets.GHCR_PAT }} --docker-email=${{ github.event.pusher.email }} --dry-run=client -o yaml | kubectl apply -f -

      - name: Helm Deploy
        run: helm upgrade --install foodbot ./helm-chart
